version: '3.8'

services:
  db:
    image: postgres:18.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Nathansno1
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db-data: